### ISSUE TITLE
what if I'm using metalsmith-sass

### ISSUE THREAD

**Issue by ninjasort** [colophonemes/metalsmith-uncss#4]
I'm using metalsmith-sass in my project, how would I point to those css files?

**Comment by colophonemes** [comment]
You just need to set whatever file `metalsmith-sass` spits out as the input file to `metalsmith-uncss`. So, if your input file is `styles/app.scss` and `metalsmith-sass` builds that to `styles/app.css` then you just need to set the input file of `metalsmith-uncss` to `styles/app.css`. 

``` js
.use(
    uncss({
            css: 'styles/app.css',
            output: 'app.min.css',
            removeOriginal: true,
    })
)
```

If you're not sure what the path of the CSS file from `metalsmith-sass` is, you can list all files in your build using:

``` js
.use(function (files, metalsmith, done) {
        console.log(Object.keys(files))
    })
```

Put that code block after `metalsmith-sass`, and the last file logged should be the path of the CSS file.
